Add statistics menu
kairoscorp/adamastor pull request #19
Opened 2018-01-20 00:21 UTC by djcouto

Add statistics menu  …
* Refactor project

* Fix animations

* Change the Settings class to singleton and add contexts methods

* Create a AppsManager to manage applications installed

2018-01-22 11:16 UTC, hgg requested changes
Please tend to the comments I've left you. Also, like discussed, change icons to their material design counterparts.

2018-01-22 11:16 UTC, hgg commented on app/src/main/java/corp/kairos/adamastor/Home/HomeActivity.java
> +            this.setLeftActivity(StatisticsActivity.class);
And context list screen to the right :+1:

2018-01-22 11:16 UTC, hgg commented on app/src/main/java/corp/kairos/adamastor/Settings/Settings.java
> +        System.out.println(zeroContext.toString());
Remove these prints please :)

2018-01-22 19:22 UTC, hgg approved these changes

2018-01-24 02:49 UTC, jlsilva1994 approved these changes
Great work indeed. Everything working and you take your time refactoring all the code, i like it 👍

2018-01-24 02:50 UTC, merged