Change all references from 'Home' to 'Leisure' and 'Travel' to 'Commute'
kairoscorp/adamastor pull request #52
Opened 2018-02-05 18:17 UTC by djcouto

2018-02-06 00:35 UTC, jlsilva1994 commented on app/src/main/res/values/strings.xml
> +    <string name="onboarding_location_description">Kairos needs to know your work and leisure location so it can better define your context depending on your location.</string>
here is better to request home location instead of leisure location. You are asking the user's home (address) location, not leisure location

2018-02-06 00:36 UTC, jlsilva1994 commented on app/src/main/res/values/strings.xml
> +    <string name="onboarding_location_leisure_label">Leisure address</string>
same here, is home address, not leisure

2018-02-06 00:39 UTC, jlsilva1994 requested changes
i leave some comments, but in general all the info related to the home location (address) like maps and label and variables related to that, shouldn't be renamed to leisure location, because we are asking the user's home location, and not the leisure location... you can be at many places and be in the leisure context, don't necessary need a leisure location.

but tell me what you think about this 👍

2018-02-06 01:15 UTC, djcouto commented
@jlsiva1994 I have change the names because I didn't want to restrict the location where you usually are in leisure context, it can be your house, a regular pub or even a open garden where you usually spend some quality time. But I agree that must of the cases makes sense to get the home location, I will fix it in the next changes 👍

2018-02-06 18:36 UTC, djcouto commented
@jlsilva1994 please review again.

2018-02-07 00:38 UTC, jlsilva1994 approved these changes
thanks to consider the changes i suggested. Approved by me

2018-02-07 17:23 UTC, merged